"""
Generate docs/world-model.md from the constants themselves.

The document and the code have to agree, and the only reliable way to make two
things agree is to derive one from the other. The prose below is hand-written;
the citation table, the unsourced list, the breakeven table and the inventory
counts are read out of the registry at generation time, so a constant that gains
a source, loses a sweep, or changes tier cannot leave a stale claim behind in
the document that is supposed to disclose it.

Usage:
    python -m sim.gen_world_model_doc
"""

from __future__ import annotations

import argparse
import os

from sim.world_model_constants import (
    REGISTRY,
    Provenance,
    breakeven_contact_fatigue,
    by_provenance,
    citation_table,
    unsourced_report,
)

PROSE_HEAD = """# World Model — Disclosed Assumptions

*Generated by `python -m sim.gen_world_model_doc`. The tables are read out of
`sim/world_model_constants.py` at generation time — do not hand-edit them.*

Backstop is evaluated against a synthetic batch, not live merchant data. That means **the person
who builds the simulator also decides who would have paid.** This document is the countermeasure:
every number the system uses is named, tiered by where it came from, and swept if it is a judgment
call.

Two separate models live in this repository, and keeping them apart is the point.

| | file | what it is |
|---|---|---|
| **The world** | `sim/world_model.py` | ground truth. Decides whether a retry actually succeeded and whether a customer actually churned. The agent has no code path to it. |
| **The agent's beliefs** | `sim/world_model_constants.py` | what Backstop thinks the world is like. Consumed through `app/scorer.Beliefs`, never read directly by scoring code. |

They use **different functional forms**, not merely different numbers — see §5.

---

## 1. How to read a constant

Three provenance tiers, declared on every constant and enforced by the dataclass:

- **`REGULATORY`** — a law or a card-network rule. Not a parameter, not sweepable, not ours. The
  dataclass raises if you try to give one a sweep range. These belong to L2a.
- **`MEASURED`** — has a published external source. Swept across the range the sources actually
  disagree over, rather than averaged into a false point estimate.
- **`ASSUMED`** — our own judgment, no public source. **Every one must declare a sweep range**; the
  dataclass raises if it does not. That is the whole point of the label.

Sources are tiered too. **PRIMARY** means the regulator, the card network, or the gateway itself.
**SECONDARY** means vendor or industry analysis — useful for magnitude, not for precision. Where
secondary sources disagree, the disagreement becomes the sweep range rather than being averaged
into a false point estimate.

**A caveat that applies to every `MEASURED` constant here:** most of the secondary sources are
dunning-vendor blogs, and a vendor marketing a retry product has an incentive to report generous
recovery numbers. Treat them as informed priors, not ground truth. That is precisely why the sweeps
exist — and it is why `P_RECOVERY_SOURCE_DISAGREEMENT` records the 20-point gap between Stripe's
published 55% Billing recovery rate and an independent audit's 25–35% rather than picking one.
"""

PROSE_UNSOURCED_TAIL = """
### `CONTACT_FATIGUE_BASE_HAZARD` deserves its own paragraph

**There is no public data tying dunning contact *count* to churn hazard. We looked.** The nearest
published figure is a Sinch consumer survey in which 26% of respondents cited too much promotional
messaging as their main reason for ending a brand relationship. That is general promotional-email
fatigue, not dunning contact count. It is **adjacent, not equivalent**, and we are not laundering it
into a citation. The constant stays `ASSUMED`, and its sweep starts at **zero** — so the adversarial
arm includes the world in which contact fatigue does not exist at all.

The defence is not a better guess. It is the threshold at which stopping beats continuing:
"""

PROSE_BODY = """
**Our conclusion holds unless a dunning contact raises churn by less than roughly two-tenths of one
percent.** That is a low bar, it is falsifiable, and it is a far stronger position than defending a
number we invented.

---

## 3. The correction to the EV specification

The expected-value model we were handed prices `STOP` at zero:

```
EV = P(recovery) x invoice_value - retry_cost
     - issuer_trust_cost x P(failure) - churn_hazard x LTV
```

It charges churn for **contacting** a customer and charges nothing for **abandoning** their invoice.
Those are not symmetric in the world. A payment that is never recovered is the definition of
involuntary churn, and it costs the remaining customer lifetime value — in the simulated world, at
roughly **seven times** what a first contact costs.

The first three-arm run demonstrated the consequence plainly: Backstop recovered 63 invoices against
the naive baseline's 87, and lost on net value by a wide margin. The scorer was not being restrained.
It was blind to half the ledger.

`P_LAPSE_IF_UNRECOVERED` was added, and every action is now credited with the lapse it prevents:

```
EV = P(recovery) x (invoice_value + P(lapse) x LTV) - action_cost
     - issuer_trust_cost x P(failure) - churn_hazard x LTV
```

This is not a tuning choice made to win a comparison. It restores the framing of a source already
cited in this document: Redux frames the true cost of a failed payment as *unrecovered failures ×
remaining LTV*, not the failed charge alone. The original formula contradicted the citation
underneath it.

---

## 4. Where restraint comes from — and where it does not

**On the contact axis, restraint emerges.** The value of a contact collapses by roughly an order of
magnitude across three asks and turns negative on the fourth — which is exactly where
`CONTACT_FREQUENCY_CAP` sits. The cap is no longer an arbitrary number defended by assertion; it
sits at the sign change, which is a much better reason for a cap to be at 3 than "3 felt right".

Recorded honestly: **this claim got weaker when the model got more correct.** Before the lapse term
was added, the crossing was at the *second* ask, comfortably ahead of the cap. It is now
*coincident* with the cap rather than ahead of it.

**On the retry axis, restraint does not emerge.** `ISSUER_TRUST_COST_INR` is about ₹8.80 — a floor
taken from a published network fee schedule — and it cannot outweigh even a fractional chance at a
₹2,000 invoice plus the lapse that recovery would prevent. Retry EV decays toward zero from above
and never crosses it. It is `MAX_LIFETIME_ATTEMPTS`, a backstop, that actually stops the retrying.

We are not fixing that by guessing a larger number. The mitigating fact, also measured: the decay is
steep enough that by the time the cap binds, under 1% of the invoice's value is left on the table.

Both findings are asserted in `tests/test_scorer.py`, so they cannot quietly stop being true.

---

## 5. The circularity problem, and what was done about it

In a simulator we write both the constants that generate outcomes and the constants the agent
optimises against. If the simulator's churn function and the agent's `churn_hazard` are the same
function, Backstop beats naive **by construction** — we told the world that contacts cause churn,
then told the agent to avoid contacts, and then reported our own premise back as a finding. A sharp
reader finds that in seconds, so the mitigation is structural rather than cosmetic:

| | the world uses | the agent believes |
|---|---|---|
| contact fatigue, shape | **saturating** exponential in contact count | **geometric** in contact count |
| patience recovery | **linear**, over 21 days | **exponential** half-life, 7 days |
| customer LTV | drawn per customer, 2–14× invoice | flat 6× invoice |
| unrecovered-invoice lapse | 0.55 | 0.55, swept 0.30–0.75 |

Neither functional form is more correct than the other; there is no public data on either. The point
is that an agent optimising a geometric belief against a saturating world has been handed the wrong
*shape*, so whatever advantage it shows is not an artefact of the two being the same equation.

`Beliefs.perturbed()` exists so the agent can be given parameters that are deliberately wrong, and
`sim/run_arms.py --belief-error` sweeps agent belief against world truth rather than moving both
together.

**Result:** across a 10× swing in the agent's churn belief (0.3× to 3×), Backstop's value added
holds within ₹1.92M–₹2.02M while its contacts fall from 65 to 47. The advantage degrades gracefully
rather than inverting. *"Our advantage survives being wrong about the constants"* is a better
sentence than *"our advantage exists when the constants are correct."*

---

## 6. Declared scope-outs

Named here rather than left silent, because silence on any of these is what a judge notices.

**Retry timing is modelled, but thinly.** Real dunning does most of its work through *when* to retry
rather than *whether* to, and a one-shot EV with no timing term would be silent on the judge's actual
problem. `RETRY_TIMING_LIFT` gives scheduling a place inside the same machinery: a deferred retry
aimed at a better moment is worth more than an immediate one. The timing itself comes, in priority
order, from

1. **a Mastercard advice code**, where the issuer attached one — MAC 24 means retry within the hour,
   25 after 24 hours, and 26–30 space attempts over 2 to 10 days. Where a MAC exists it overrides our
   own estimate, which is the cheapest possible answer to "where does your retry timing come from?".
   Many Indian issuers do not attach them consistently, so absence is itself a signal L1 must handle;
2. **the 28th–31st Indian payday window**, for `SOFT_FUNDS` only — no other class has an external
   cash-flow mechanism, and inventing a timing story for a gateway timeout would be assumption for
   its own sake;
3. **nothing**, in which case deferral buys nothing.

The *magnitude* of the lift is ours, and is swept down to 1.0, where timing buys nothing at all.

Note the collision this creates, and which way we resolve it: on the e-mandate rail, the RBI 24-hour
pre-debit notice makes MAC 24's "retry within the hour" **unfollowable**. Where the card network and
the regulator disagree, the regulator wins.

**`ESCALATE_HUMAN` is not priced.** Pricing it needs a cost for an analyst's time, for which we have
no source and would have to invent one. It stays outside the scorer's candidate set and remains
L2a's disposition for a risk decline — a disposition, not an economic choice.

**The value of information is ignored.** A retry that fails tells us something about the invoice, and
a strictly correct treatment would price that. It does not, and the omission biases the scorer toward
stopping slightly too early.

**Ground-truth labels are exact by construction**, not hand-annotated, because the data is synthetic.
That is a real limitation of the evaluation and not a strength of it.

---

## 7. Full provenance table

"""

PROSE_TAIL = """

---

## 8. Change log against the original day-1 document

The first version of this document described `sim/world_model.py`'s hazard model using a
`MEASURED_*` / `ASSUMED_*` naming convention. That model is still here, and it is still the world's
truth. What changed:

- The three-tier provenance scheme (`REGULATORY` / `MEASURED` / `ASSUMED`) with tiered sources
  replaced the two-way prefix convention, and moved into a dataclass that enforces its own rules —
  an `ASSUMED` constant without a sweep range now raises at import.
- A **world churn process** was added (§5). The original model had no way for a customer to be lost,
  only for an invoice to fail, so there was nothing for restraint to protect.
- **`ASSUMED_WORLD_UNRECOVERED_CHURN` was added.** Without it, stopping is free, the optimal policy
  is to stop on everything, the frontier chart collapses to a single point at the origin, and the
  demo is boring. With it, both doing too much and doing too little cost real money, which is the
  only configuration in which an efficient frontier exists at all.
- **A bug in the batch oracle was fixed.** `MEASURED_AUTH_HAZARD_1 = 0.55` describes a *fresh link* —
  its own docstring says "a fresh link removes the original friction" — but the oracle was rolling it
  as the *retry* hazard. Ground truth was therefore rewarding re-presentment of cards whose owners
  had walked away from an OTP screen, which contradicts both the failure taxonomy and the structural
  zero in `CHANNEL_FIT`, and handed the naive arm a block of free recoveries for doing the one thing
  every source agrees does not work.
"""


def build() -> str:
    counts = {p: len(by_provenance(p)) for p in Provenance}
    sweepable = len([c for c in REGISTRY.values() if c.sweep is not None])

    inventory = (
        f"\nCurrent inventory: **{counts[Provenance.REGULATORY]} regulatory**, "
        f"**{counts[Provenance.MEASURED]} measured**, "
        f"**{counts[Provenance.ASSUMED]} assumed**, across "
        f"**{sweepable} sweepable parameters**.\n\n---\n\n"
        "## 2. The constants we could NOT source\n\n"
        "This is the section to read first, because it is where the project is weakest and the\n"
        "weakness is load-bearing.\n\n"
    )

    # unsourced_report() ships its own H2; strip it so the numbering here holds.
    unsourced = unsourced_report().split("\n", 1)[1].strip()

    breakeven = ["\n| customer LTV | breakeven per-contact churn hazard |", "|---|---|"]
    for m in (2.0, 6.0, 12.0, 18.0):
        breakeven.append(f"| {m:.0f}× invoice | {breakeven_contact_fatigue(ltv_multiple=m):.4%} |")

    return (
        PROSE_HEAD
        + inventory
        + unsourced
        + "\n"
        + PROSE_UNSOURCED_TAIL
        + "\n".join(breakeven)
        + "\n"
        + PROSE_BODY
        + citation_table()
        + PROSE_TAIL
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=str, default="docs/world-model.md")
    args = ap.parse_args()
    doc = build()
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(doc)
    print(f"Wrote {args.out} ({len(doc):,} bytes)")


if __name__ == "__main__":
    main()
